### ISSUE TITLE
Unable to install through conda in Qiime environment - "ImportError: No module named 'minstrel.q2'"

### ISSUE THREAD

**Issue by gibsramen** [mortonjt/minstrel#18]
I am trying to install through conda in a Qiime environment but I am receiving an error when calling the plugin. Conda says the package is installed correctly but calling `qiime minstrel --help` returns 

`QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Traceback (most recent call last):
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/commands.py", line 99, in get_command
    plugin = self._plugin_lookup[name]
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/commands.py", line 75, in _plugin_lookup
    import q2cli.cache
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 301, in <module>
    CACHE = DeploymentCache()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'minstrel.q2'`

I also tried `qiime dev refresh-cache` and received a similar error:

`QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Traceback (most recent call last):
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/dev.py", line 27, in refresh_cache
    import q2cli.cache
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 301, in <module>
    CACHE = DeploymentCache()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/q2cli/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/Users/gibraanrahman/miniconda3/envs/qiime2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'minstrel.q2'`

**Comment by charles-cowart** [comment]
This looks to be packaging related, as @fedarko and myself have both attempted to install this in Qiime2-installed environments (2019.1, etc.).

**Comment by fedarko** [comment]
@mortonjt yeah -- we've managed to replicate this error in both Q2 2018.8 and 2019.1, so it seems like it might be an error in how minstrel and QIIME 2 interact (since minstrel seems to work fine by itself, but when we install it into a Q2 environment things start to go wrong).

**Comment by mortonjt** [comment]
Hmm. The pip install should work.
Although, I've seen this problem a bit myself (since the q2 plugin is still
WIP).

That being said, I have been able to get this installed in the most recent
q2 environment (2019.1). May require git clone followed by pip install -e
 . In the root folder.

**Comment by fedarko** [comment]
Can confirm that running

```bash
git clone https://github.com/mortonjt/minstrel.git
cd minstrel
pip install -e .
```
in my QIIME 2 conda environment solved the problem for me -- now I can refresh the QIIME cache and run `qiime minstrel --help` without getting the import error. @gibsramen could you try this?

Since this resolves the error, it seems like the problem comes up somehow due to installing minstrel via `pip install h5py git+https://github.com/mortonjt/minstrel.git`.

Thanks Jamie! :)

**Comment by charles-cowart** [comment]
I'll look into the details of it. For now, it may help to update the
install docs to reflect the change to pip. @Jamie Morton
<jamietmorton@gmail.com>, I can do this if you're busy.

**Comment by jamie** [comment]
cc @mortonjt

**Comment by gibsramen** [comment]
> Can confirm that running
> 
> ```shell
> git clone https://github.com/mortonjt/minstrel.git
> cd minstrel
> pip install -e .
> ```
> 
> in my QIIME 2 conda environment solved the problem for me -- now I can refresh the QIIME cache and run `qiime minstrel --help` without getting the import error. @gibsramen could you try this?
> 
> Since this resolves the error, it seems like the problem comes up somehow due to installing minstrel via `pip install h5py git+https://github.com/mortonjt/minstrel.git`.
> 
> Thanks Jamie! :)

This worked for me. Thank you everyone!
